### ISSUE TITLE
移植其他模型问题

### ISSUE THREAD

**Issue by konodiavo** [HomiKetalys/gd32ai-modelzoo#1]
请问大佬如果想自己重新换模型改应用方向的话，怎么生成edgeai的那些东西呢 想用gd32h759的start板做故障分类

**Comment by HomiKetalys** [comment]
不是图像类任务吗，那可能有点麻烦。edgeai中的主要代码一是模型推理用的代码，这部分是用X-CUBE-AI生成的，二是模型推理函数调用简化的代码模板，这部分内容是任务相关的。你可以用X-CUBE-AI来生成第一部分的代码，第二部分代码你可以参考`common_utils/c_codes`中的两个图像类任务模板进行编写。

**Comment by konodiavo** [comment]
谢谢大佬 我昨天自己也琢磨了下 准备照着开发文档调用api自己慢慢来了
