### ISSUE TITLE
推理结果画框偏移问题

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [HomiKetalys/gd32ai-modelzoo#10]
哥，您屏幕大小和我现在用的屏幕大小不一样，这个推理结果画框出现x轴偏移是不是正常的？
您的：
![image](https://github.com/user-attachments/assets/f8b5ea27-3588-4720-ad7e-1780b8f90a12)
我们的：
<img width="180" alt="e441cb2c0ffdd7b6975978c6c5cb2bd" src="https://github.com/user-attachments/assets/54567074-c707-4811-85b9-4a654ca84574">
我们是不是得修改这两句代码：
![image](https://github.com/user-attachments/assets/21ae7be0-0c0f-4cea-b87b-4f2d988fd7a5)

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 你可以先尝试绘制一个xyxy=[0,0,100,100]的框看看是不是目标框的绘制问题。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
哥，应该是推理后得到框数据结果问题，类别正确识别但是画的框有偏移，估计我们是小目标，在量化后的模型，有出入。

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 一般来说不会偏移太严重，你的是偏移大概多少呢。我确认一下是不是目标框解码部分写错了。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
我给您拍了几张推理的结果，红色框是真实标签。
我是将图片转为RGB565的格式去推理的。
结果1：<img width="1137" alt="a40bf7cf2f31f07a46b46e20a413cc6" src="https://github.com/user-attachments/assets/d7247035-b94d-41e9-b947-62de6b537dd0">
结果2：
<img width="640" alt="d07e8b15bc64191bc9c71f74a97c5b7" src="https://github.com/user-attachments/assets/6e79c72f-f497-4953-b037-3d0b1810b327">
结果3：
<img width="1137" alt="e9861744a5d14931a3e0482d2d83902" src="https://github.com/user-attachments/assets/3c2e2097-f669-48a2-9348-05e5fc5db4ab">
运行部署代码时验证采用测试数据集，结果：
<img width="1252" alt="6f57a0c678f46f502d94cb621dc3369" src="https://github.com/user-attachments/assets/6a9d2828-d801-4a4b-ba16-a380f9a6f0b7">

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
从评价指标来看模型效果还是很不错哒，哥

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 感觉像是x轴反了，你试试在绘制目标框时加上图中这句来临时解决这个问题。
![image](https://github.com/user-attachments/assets/0f29680f-ab69-4e18-8cc7-b46d875b1588)
不过实际上预测结果是正确的，你检查一下你的读取图像的方式和图像的绘制方式的实现是否一致
![image](https://github.com/user-attachments/assets/e019e9ba-d690-418e-a934-abcd25a1bea1)
![image](https://github.com/user-attachments/assets/8e3fb569-c16d-4f36-85f3-6e163da8c455)

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
哥，就是X轴方向反了，您简直就是天上的文曲星，地上的活菩萨，爱您，哈哈哈哈哈。
