### ISSUE TITLE
训练自己数据集出现准确率等全为0，任务是小目标检测。

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [HomiKetalys/gd32ai-modelzoo#5]
![zx](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/6606fc64-db21-46b6-87e9-c83ea57101cb)
哥有些问题想请教你。
问题一：这个问题是模型的问题吗？
问题二：我有训练好的YOLOv8模型怎么可以像yolofastv2一样转为AI吗？

**Comment by HomiKetalys** [comment]
> ![zx](https://private-user-images.githubusercontent.com/86902247/339323551-6606fc64-db21-46b6-87e9-c83ea57101cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzgwMzYsIm5iZiI6MTcxODI3NzczNiwicGF0aCI6Ii84NjkwMjI0Ny8zMzkzMjM1NTEtNjYwNmZjNjQtZGIyMS00NmI2LTg3ZTktYzgzZWE1NzEwMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDExMjIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTNiMjcxY2I1NTZkZDJkNjMyNzIxMGM5Y2JjMmJhMWJjMjIyZDMwZDJjY2JkZDcwYWZlYTM4OGNmNGM2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rB9d84aY43cSvG-nb6DEeP_UodS5qzcHI0MDT5V4XE) 哥有些问题想请教你。 问题一：这个问题是模型的问题吗？ 问题二：我有训练好的YOLOv8模型怎么可以像yolofastv2一样转为AI吗？

@zxzxzxzxzxzxzxzxzxzxzx 小目标检测一般来说要很高的分辨率，256x256效果会很差。但是对于MCU来说，高分辨率带来的计算量是难以接受的。yolofastv2在256x256分辨率下可以接受的目标分辨率大小大约在32x32。YOLOv8参数量，计算量以及内存占用对于MCU来说都太高了，即使转了也运行不了。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
数据集原图片大小是600*600的，那我现在想的是通过基于标注框的信息以256*256大小裁剪数据集照片，这样操作会不会可以解决这个问题。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
目前我们已经将您的训练好的模型迁移到了GD32H757ZM上了

**Comment by HomiKetalys** [comment]
> 数据集原图片大小是600_600的，那我现在想的是通过基于标注框的信息以256_256大小裁剪数据集照片，这样操作会不会可以解决这个问题。

当然可以，不过我建议你根据标注框的大小进行裁剪，比如标注框分辨率为10x10，你的裁剪框可以在20(2倍)到100(10倍)间随机取。当然为了防止标注框只在裁剪框中间，你可以再次随机取裁剪框的起点保证标注框在裁剪框各处都有可能出现。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
非常感谢您为我提供的帮助，哥。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
哥，我已经完成了训练，但是在模型量化后，却检测不出目标，没量化前可以推理出来，这个问题这么去调试解决呢？
未量化前：
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/d938d92d-aeab-49c8-a88b-4acc7e35b369)
量化后：
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/aa61de1d-bcc7-4fff-bee1-f8a30a58f53d)
量化配置deploy.py：
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/7d8a9b84-b7d9-4bac-9a24-6c89ddb213ed)
量化过程中有几个警告：
1、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\losses.py:2978: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
2、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
3、WARNING:Quantization DataLoder ::2166 images detected, the number of recommended images is less than 100.
输出结果：
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/371d8cc1-ec50-4eb1-99ac-2cac86763dcf)
量化后的推理文件：
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/f9bcbcc8-fb9b-4fe4-9644-0e4372819d85)
未量化推理文件：来自于：https://github.com/dog-qiuqiu/Yolo-FastestV2/blob/main/test.py
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/14a22304-b873-4fc3-975b-1da1df2ceb43)

**Comment by HomiKetalys** [comment]
> 哥，我已经完成了训练，但是在模型量化后，却检测不出目标，没量化前可以推理出来，这个问题这么去调试解决呢？ 未量化前： ![image](https://private-user-images.githubusercontent.com/86902247/339951069-d938d92d-aeab-49c8-a88b-4acc7e35b369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTEwNjktZDkzOGQ5MmQtYWVhYi00OWM4LWE4OGItNGFjYzdlMzViMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDY2MGMxNDc4MzhkYzUyMDFkMDM3ZjZmNmVlMDk0MjcyNTk2Yjg2M2Y1NjIxNmUwNzBjNjk5NmZiODI0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZbsgVhkfkcKe7eTDeRk-F0CI7cD5ZYdSaa5Ot4IO-sU) 量化后： ![image](https://private-user-images.githubusercontent.com/86902247/339951107-aa61de1d-bcc7-4fff-bee1-f8a30a58f53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTExMDctYWE2MWRlMWQtYmNjNy00ZmZmLWJlZTEtZjhhMzBhNThmNTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMDllY2MwMzQzZWQ4MzcwNDYxMzJlYWNkNjMwMmE4OGQzYmMyZDY5YjkxMzdkMDhiZGI3MzNlZmNkYTBmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hK517aV1whDJ0s4U2-FPSfPMmixUC6j1KnhPRTXFWU8) 量化配置deploy.py： ![image](https://private-user-images.githubusercontent.com/86902247/339951158-7d8a9b84-b7d9-4bac-9a24-6c89ddb213ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTExNTgtN2Q4YTliODQtYjdkOS00YmFjLTlhMjQtNmM4OWRkYjIxM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjllMzFlNWE0MmQwNWRmOTZiOTliNmM4ZjM1YmIzOWQ5MjZlYzU0ZGVjZGRjYzViOTY1ZjMyMDMwZTljYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yaI4JsgQlCYsYqmW1BZuV7S2zNjvQMo3w0e0c99MB1c) 量化过程中有几个警告： 1、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\losses.py:2978: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead. 2、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead. 3、WARNING:Quantization DataLoder ::2166 images detected, the number of recommended images is less than 100. 输出结果： ![image](https://private-user-images.githubusercontent.com/86902247/339951243-371d8cc1-ec50-4eb1-99ac-2cac86763dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTEyNDMtMzcxZDhjYzEtZWM1MC00ZWIxLTk5YWMtMmNhYzg2NzYzZGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTQyODkzM2RjZTU5ZTY2NzY3YWJiMDA5ZWI4NGEzNmQzYWI3MmJjMWJhY2ExYjA0OWQ0YTliNjI0MTAyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8MR_l-gRrI-ubhA694I_ze3UvQcJs0i2Hp0wXeRoXLA) 量化后的推理文件： ![image](https://private-user-images.githubusercontent.com/86902247/339951258-f9bcbcc8-fb9b-4fe4-9644-0e4372819d85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTEyNTgtZjliY2JjYzgtZmI5Yi00ZmU0LTk2NDQtMGU0MzcyODE5ZDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMmIzNzEzOTkxNzRkMTRlNzAwYzUyNzllZGJmODU4OTgxZmJiNzA5N2E5NWYyODFkMzI5Y2E4ZGM4NjE5MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9DOcPUXpsBOs9_F_OKewyRNmp53Uq8n9Dxrsg0a6-PA) 未量化推理文件：来自于：https://github.com/dog-qiuqiu/Yolo-FastestV2/blob/main/test.py ![image](https://private-user-images.githubusercontent.com/86902247/339951293-14a22304-b873-4fc3-975b-1da1df2ceb43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg0MjgsIm5iZiI6MTcxODQyODEyOCwicGF0aCI6Ii84NjkwMjI0Ny8zMzk5NTEyOTMtMTRhMjIzMDQtYjg3My00ZmMzLTk3NWItMWRhMWRmMmNlYjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDAxZTYzMDFkYTI1MmYxMmU2Y2JkOGNmOTA1MmM2Y2ZmZWFkYmJmYjA4ODlkMWQzZDVjOGUzZWYwYjUzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2feY-kdCH9rywcUADZEG4XiBS-jrzIiDEhJ3nfIFXXA)

@zxzxzxzxzxzxzxzxzxzxzx  你可以先对tflite文件和onnx文件在同一张图片上进行推理，看看两者的输出结果是否接近，如果接近则可以先排除量化的问题，或者你可以将onnx和tflite文件发给我，我看看是怎么回事。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
哥，我已经邮件发您了一个文件，我自己也去找找资料看看。



---原始邮件---
发件人: "Homi ***@***.***&gt;
发送时间: 2024年6月15日(周六) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HomiKetalys/gd32ai-modelzoo] 训练自己数据集出现准确率等全为0，任务是小目标检测。 (Issue #5)




  
哥，我已经完成了训练，但是在模型量化后，却检测不出目标，没量化前可以推理出来，这个问题这么去调试解决呢？ 未量化前：  量化后：  量化配置deploy.py：  量化过程中有几个警告： 1、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\losses.py:2978: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead. 2、WARNING:tensorflow:From D:\conda\envs\tf\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead. 3、WARNING:Quantization DataLoder ::2166 images detected, the number of recommended images is less than 100. 输出结果：  量化后的推理文件：  未量化推理文件：来自于：https://github.com/dog-qiuqiu/Yolo-FastestV2/blob/main/test.py 
  
@zxzxzxzxzxzxzxzxzxzxzx  你可以先对tflite文件和onnx文件在同一张图片上进行推理，看看两者的输出结果是否接近，如果接近则可以先排除量化的问题

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/130334067/485a52ac-ca5c-4799-a0cd-032134c9579a)
量化后的tflite模型和原onnx模型计算结果相近，说明量化没有问题。你可以直接先部署到MCU上试试

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
那有点奇怪啦，我再调试看看。感谢🙏哥



---原始邮件---
发件人: "Homi ***@***.***&gt;
发送时间: 2024年6月15日(周六) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HomiKetalys/gd32ai-modelzoo] 训练自己数据集出现准确率等全为0，任务是小目标检测。 (Issue #5)




 
@zxzxzxzxzxzxzxzxzxzxzx
 image.png (view on web)
 量化后的tflite模型和原onnx模型计算结果相近，说明量化没有问题。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/1f076a25-9c46-41d4-81bd-4ffbfc4b4b13)

![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/f7a7500b-a938-463f-90da-05ceef3a7568)

哥这里是不是要改来对应上

**Comment by HomiKetalys** [comment]
> ![image](https://private-user-images.githubusercontent.com/86902247/340069913-1f076a25-9c46-41d4-81bd-4ffbfc4b4b13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjg2MjIsIm5iZiI6MTcxODUyODMyMiwicGF0aCI6Ii84NjkwMjI0Ny8zNDAwNjk5MTMtMWYwNzZhMjUtOWM0Ni00MWQ0LTgxYmQtNGZmYmZjNGI0YjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MjViZDM2MjQxNmJkOGQ5YzU1NzcyZTViNTg4YTBlNmEzM2FkNzYwNjBmOTE1MWU5NDlhOWNhNmNjZjMyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ASnnq1Yju9tpi8lwJzxVkEcpnBL6n_9mw_8xZ9jTN7c)
> 
> ![image](https://private-user-images.githubusercontent.com/86902247/340069929-f7a7500b-a938-463f-90da-05ceef3a7568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjg2MjIsIm5iZiI6MTcxODUyODMyMiwicGF0aCI6Ii84NjkwMjI0Ny8zNDAwNjk5MjktZjdhNzUwMGItYTkzOC00NjNmLTkwZGEtMDVjZWVmM2E3NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNWJlMjg5MzIyMzczMjI0NjU4ODQzMzViNDdjMWI1MDEzNDY3ODA2OWNmNmZlYTc1MTAyODk1MjhjOGM0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A43tKFg9_4ZaT74kpMvlvr1m17R7pcCpKJB-LUicxp0)
> 
> 哥这里是不是要改来对应上

@zxzxzxzxzxzxzxzxzxzxzx 不用改，GD32H7用不了X-CUBE-AI的CM7版本的库
