### ISSUE TITLE
yolov5n 剪枝后模型部署

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [HomiKetalys/gd32ai-modelzoo#7]
哥，我又来了哈哈哈哈。
> 问题一
yolofastv2对于我的场景效果太差了，我目前对yolov5进行剪枝和蒸馏，权衡好精度和大小，有可能部署吗？
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/281024cf-e4ef-4da5-9543-aeaef0a6c1ac)
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/2a217955-d87e-46f4-9954-e4e5c4486ce1)

> 问题二
我想将处理好的模型onnx转为c，根据网上的资料会使用我的是GD32H757z芯片。
![image](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/6fe90812-30fa-475e-a40e-c15b6b44b65d)
这里如何选择呢？

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx  对于问题一，关键在于峰值内存的大小，你可以算算你的第一层卷积后的特征图的大小，比如特征图形状160x160x32，则此时内存占用至少占用800KB。当然一般来说第一场卷积后的特征图占用内存是最多的，别的地方也有可能，比如类似特征融合FPN部分。如果你能控制峰值内存大小小于600KB，那应该是没问题的。对于问题二，在STM32IDE中的芯片选择只要能保证最终代码能生成就可以随便选，因为8.0.1版本及以上的X-CUBE-AI在内存不够时会拒绝生成代码，在保证内存足够的情况下，你选的应该没问题。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![fb03120e81985c6425fabe33b7c5a3e](https://github.com/HomiKetalys/gd32ai-modelzoo/assets/86902247/ebc1385b-2082-43ff-9a7b-0978c1e6c052)
模型峰值内存占用,是要符合在SRAM的量程就行。

**Comment by HomiKetalys** [comment]
> ![fb03120e81985c6425fabe33b7c5a3e](https://private-user-images.githubusercontent.com/86902247/341177739-ebc1385b-2082-43ff-9a7b-0978c1e6c052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MjM0MjIsIm5iZiI6MTcxODgyMzEyMiwicGF0aCI6Ii84NjkwMjI0Ny8zNDExNzc3MzktZWJjMTM4NWItMjA4Mi00M2ZmLTlhN2ItMDk3OGMxZTZjMDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE4NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOTA1Y2I3ZWViMDJiMzMzODIxYTJmOTc5MWRmODY2Njc1YmI3NjRiY2EwODc2NzUyZDhjNzMwN2FlZjUxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8qsZkQWXIrPa00xd-xeninHiJubXmpWsFWA0kwl8laI) 模型峰值内存占用,是要符合在SRAM的量程就行。

@zxzxzxzxzxzxzxzxzxzxzx 是的

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
谢谢哥
