### ISSUE TITLE
export.py执行维度问题报错。

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [HomiKetalys/gd32ai-modelzoo#8]
您好，我在完成yolov10自己数据集训练后，想导出tflite文件时，执行 python export.py --yaml results/train/coco_80_0002/coco_80.yaml --weight results/train/coco_80_0002/weights/weight_AP05_-1.000000_300_epoch.pth --convert_type 1 --tflite_val_path "data/COCO2017_256/images/val_image" --eval True 遇到一个数据维度的报错。

![image](https://github.com/user-attachments/assets/d8a33d1a-dd92-4841-a744-c334bd2d4c0d)
box这里有四个维度，但是只有三个变量接受。
![image](https://github.com/user-attachments/assets/cc32924f-cce0-46ba-b8ad-a796a87848ea)
我是哪里没有设置正确吗？

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 
将
```
b, _, a = box.shape
box=box.view(b, 4, self.reg_max, a).softmax(2).view(b,-1,a)
```

修改为

```
 b, _, h,w = box.shape
 box=box.view(b, 4, self.reg_max, h*w).softmax(2).view(b,-1,h,w)
```
应该能解决这个问题。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
感谢您的解答，成功解决了。
