### ISSUE TITLE
C代码生成的问题

### ISSUE THREAD

**Issue by zxzxzxzxzxzxzxzxzxzxzx** [HomiKetalys/gd32ai-modelzoo#9]
哥，我想请教一下：
![image](https://github.com/user-attachments/assets/f35f0c20-b58c-43ce-b1b7-12e46d6b1535)
这段生成的C代码的指令，运行了2个小时还在运行, 正常吗？
![image](https://github.com/user-attachments/assets/3f980636-7dec-4ac9-bbf7-d0e113b43e66)
按照Issue里面的复制文件，操作的。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
我的是windows系统，这个会不会bug比较多？

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/user-attachments/assets/572021b8-1fe1-4f93-9179-da44683bdc67)
我看后台这个进程是存在的，哥

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 可以复制命令在命令行运行试一下，我看看是不是命令有问题

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
OK，我的哥。
![image](https://github.com/user-attachments/assets/1a0a909d-ca26-4f5f-ad1b-7dae3d2e6684)
![image](https://github.com/user-attachments/assets/c908bc40-71bf-4e0f-bad4-723b74dd3fe6)

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/user-attachments/assets/f7b525d1-296d-4dd8-a912-9b1fb47b583e)
ka卡在这里不动了。
还有一个就是导出tflite二进制文件时，这个标红的文件里是空的。
![image](https://github.com/user-attachments/assets/52d159c5-8fac-44ca-a180-657a3b6b85de)

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 这就有点奇怪了,可能8.1.0版本X-CUBE-AI有我不知道的bug，我明天再看看。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
好的，我换了两个版本（8.1.0和8.0.1）都是这样怪怪的.

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 我注意到你这命令行有提示
![image](https://github.com/user-attachments/assets/42957705-0c4e-45ca-a3d2-8cc2f19d572f)
可能在第一次运行X-CUBE-AI会出现这个提示，你在命令行再运行一次，输入y或n。看能不能得到生成的代码。然后再试试用python一次看会不会卡住。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
明白啦哥，我按照您的建议试试。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
哥你就是我的神呀~  OK啦

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/user-attachments/assets/c0a9b4bc-257f-4bb9-84c4-242ce0c2ad99)
哥，生成的代码，更新在这个路径下了，没有在deploy文件里，是否正常呢？是否可以修改文件保存的路径啊？哥
![image](https://github.com/user-attachments/assets/79d69158-c42c-4042-b4a4-2d5bf229d483)

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/user-attachments/assets/cf178646-a694-4afe-9d9b-1156dbf355bb)
![image](https://github.com/user-attachments/assets/e969814c-7ebd-4cf0-8f8e-8c376304edb2)
根据代码来看，是生成在哪里的，明白了，哥。有点啰嗦啦

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
![image](https://github.com/user-attachments/assets/f03f6e67-4ac3-46f0-b0d0-f6c20a6f6994)
哥，我看你的是在deploy文件中的，是您手动移动过来的吗？

**Comment by HomiKetalys** [comment]
@zxzxzxzxzxzxzxzxzxzxzx 这是我给的样例，手动移动的。modelzoo文件夹里的都是样例。`--c_project_path`为None就是默认保存在deploy/xxxx_00xx下。为文件夹路径就保存在对应文件夹中。为uvprojx文件路径就保存在其同级文件夹中。我给的示例代码是uvprojx文件路径，这样不仅会生成Edge_AI文件夹，还会自动将.h文件和.c文件添加进uvprojx文件，这样就不用再keil5中自己配置了。

**Comment by zxzxzxzxzxzxzxzxzxzxzx** [comment]
太棒啦！哥。真嘟强。向开源的伟大精神膜拜
